//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clases_x_Alumnos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clases_x_Alumnos()
        {
            this.Nota = new HashSet<Nota>();
        }
    
        public int idClases_x_Alumnos { get; set; }
        public string EstadoDePago { get; set; }
        public bool Eliminado { get; set; }
        public int UsuarioCreacionId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int UsuarioModificacionId { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public int Clase_idCurso { get; set; }
        public int Alumno_idAlumno { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Clase Clase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nota> Nota { get; set; }
    }
}
