//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clase()
        {
            this.Clases_x_Alumnos = new HashSet<Clases_x_Alumnos>();
        }
    
        public int idCurso { get; set; }
        public string TipoDeClase { get; set; }
        public int AforoMaximo { get; set; }
        public double Precio { get; set; }
        public string TipoDeLicencia { get; set; }
        public string IntervadoDeHoras { get; set; }
        public string NombreProfesor { get; set; }
        public bool Activo { get; set; }
        public bool Eliminado { get; set; }
        public int UsuarioCreacionId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int UsuarioModificacionesId { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public int Usuario_IdUsuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clases_x_Alumnos> Clases_x_Alumnos { get; set; }
    }
}
